# Dockerfile.worker
FROM python:3.10-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
CMD ["sh","-c","celery -A tasks.trading_tasks.celery_app worker --loglevel=info --concurrency=2"]
